name: CI Pipeline
run-name: Action by @${{ github.actor }}
on: 
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install jest
    - run: npm install --save-dev node-fetch
    - run: npm install -D jest-environment-jsdom
    - run: npm ci -l verbose
    - name: Run TESTS
      run: npm run test
      env:
        NODE_OPTIONS: --experimental-vm-modules
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install eslint
    - run: npm ci -l verbose
    - name: Run ESLINT
      run: npm run lint
  jsdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build JSDOCS
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./assets/scripts
        recurse: true
        output_dir: ./jsdocs
        front_page: README.md
        template: clean-jsdoc-theme
    - name: Commit JSDOCS
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: noreply@github.com
        message: 'Generated JSDocs'
        add: 'jsdocs/*'
  deploy:
    needs: [test, lint, jsdocs]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
