name: CI Pipeline
run-name: Action by @${{ github.actor }}
on: 
  push:
    branches:
    - main
  pull_request:
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install jest
    - run: npm install --save-dev node-fetch
    - run: npm install -D jest-environment-jsdom
    - run: npm ci -l verbose
    - name: Run TESTS
      run: npm run test
      env:
        NODE_OPTIONS: --experimental-vm-modules
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install eslint
    - run: npm ci -l verbose
    - name: Run ESLINT
      run: npm run lint
  jsdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build JSDOCS
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./assets/scripts
        recurse: true
        output_dir: ./jsdocs
        front_page: README.md
        template: clean-jsdoc-theme
    - name: Commit JSDOCS
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: noreply@github.com
        message: 'Generated JSDocs'
        add: 'jsdocs/*'
  deploy:
    needs: [test, lint, jsdocs]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
