name: CI Pipeline
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install jest
    - run: npm install --save-dev node-fetch
    - run: npm install -D jest-environment-jsdom
    - run: npm install eslint
    - run: npm ci -l verbose
    - name: Run TESTS
      run: npm run test
      env:
        NODE_OPTIONS: --experimental-vm-modules
    - name: Run ESLINT
      run: npm run lint
    - name: Build JSDOCS
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./assets/scripts
        recurse: true
        output_dir: ./jsdocs
        front_page: README.md
    - name: Commit JSDOCS
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: noreply@github.com
        message: 'Generated JSDocs'
        add: 'jsdocs/*'
