name: CI Pipeline
run-name: Action by @${{ github.actor }}
on: 
  push:
    branches:
    - main
  workflow_dispatch:
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Installs
      run: |
        npm install jest
        npm install --save-dev node-fetch
        npm install -D jest-environment-jsdom
        npm install -g @percy/cli
        npm ci -l verbose
    - name: Start server
      run: |
        npm start &
      env:
        CI: true
    - name: Run TESTS
      run: percy exec -- npm run test
      env:
        NODE_OPTIONS: --experimental-vm-modules
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Installs
      run: |
        npm install eslint
        npm ci -l verbose
    - name: Run ESLINT
      run: npm run lint
  jsdocs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build JSDOCS
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./assets/scripts
        recurse: true
        output_dir: ./jsdocs
        front_page: README.md
        template: clean-jsdoc-theme
    - name: Commit JSDOCS
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: noreply@github.com
        message: 'Generated JSDocs'
        add: 'jsdocs/*'
  minify:
    needs: [test, lint, jsdocs]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Fetch newest version
      run: git pull
    - name: Set up Node
      uses: actions/setup-node@v3
    - name: Installs
      run: |
        npm install uglify-js -g
        sudo apt-get update
        sudo apt-get install jpegoptim -y
        sudo apt-get install pngquant -y
    - name: Minify JS
      run: find ./assets/scripts -name "*.js" -exec uglifyjs {} -o {} --compress --mangle --module \;
    - name: Compress JPEGs
      run: |
        find -name "*.jpeg" -print0 | xargs -0 -I {} sh -c 'jpegoptim --strip-all --all-progressive "{}" || echo "Failed to process {}"'
        find -name "*.jpg" -print0 | xargs -0 jpegoptim --strip-all --all-progressive
    - name: Compress PNGs
      run: |
        find -name "*.png" -exec pngquant --force --ext .png {} \;
    - name: Clean everything
      run: |
        rm -r -f __tests__
        rm README.md
        rm license.txt
        rm package.json
    - name: Push to new branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'noreply@github.com'
        git branch -D gh-pages || true 
        git checkout -b gh-pages
        git add .
        git commit -m "Minified JS and compressed image files"
        git push -f origin gh-pages
  deploy:
    needs: [minify]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        ref: gh-pages
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

